name: Check Markdown links

on:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches:
      - main
  pull_request: {}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'src/tokens/erc20, src/tokens/erc721'
